### ISSUE TITLE
S3 Express One AZ Support

### ISSUE THREAD

**Issue by hustshawn** [awslabs/mountpoint-s3-csi-driver#91]
/feature

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Not sure if current S3 mountpoint CSI driver can support S3 express or not. I tried with existing static provision example, but it failed. If it is already supported transparently, would suggest to have either an example or doc for it. I am also would like to contribute for the example if it's already supported.

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by dlakhaws** [comment]
Thank you for the feature request! We are currently actively working on this feature and our ETA is to have a new release that supports Mountpoint version 1.3.1 (which supports S3 Express One Zone) by the end of this week! Will update you when this release is cut.

**Comment by dlakhaws** [comment]
We've released v1.1.0 of the driver which includes support for S3 Express One Zone! Here's an [example](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/s3_express_specify_az.yaml) which includes how to set the availability zone of the pod as well.

**Comment by hustshawn** [comment]
Hi @dlakhaws , thanks for your update. I noticed the v1.1.0 has not been released as EKS managed addons, as of today Dec 7. So I just mannually updated my s3-csi-driver image from the daemonset. 

However, it is still not able to mount the the s3 express volume, and got below errors.
```
Error: Failed to create mount process
  Warning  FailedMount  114s  kubelet  MountVolume.SetUp failed for volume "s3-express-pv" : rpc error: code = Internal desc = Could not mount "s3-express-us-east-1a--use1-az4--x-s3" at "/var/lib/kubelet/pods/7d0b8db4-0707-4529-96ce-3ebdc4e5925c/volumes/kubernetes.io~csi/s3-express-pv/mount": Mount failed: Failed to launch systemd service mount-s3-1.3.1-84ca2a50-ac1d-44db-9c77-a9a2fb7f930a.service output: Error: Failed to create S3 client\r
\r
Caused by:\r
    0: initial ListObjectsV2 failed for bucket s3-express-us-east-1a--use1-az4--x-s3 in region us-east-1\r
    1: Client error\r
    2: Unknown CRT error\r
    3: CRT error 14343: aws-c-s3: AWS_ERROR_S3_INVALID_RESPONSE_STATUS, Invalid response status from request\r
Error: Failed to create mount process
  Warning  FailedMount  73s (x4 over 8m5s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
```
I did have the bucket created, and specified correct region and AZ; also for the IAM role I already gave s3 full access to simplify the testing. So do you have any hints?

**Comment by hustshawn** [comment]
You are right @dlakhaws . It's working now with the policy you suggested. I was not aware it is a separate permission group for S3 Express. Thank you so much
